[package]
name = "tower_allowed_hosts"
version = "0.2.0"
edition = "2021"
authors = ["Saurav Sharma <appdroiddeveloper@gmail.com>"]
homepage = "https://github.com/iamsauravsharma/tower_allowed_hosts"
repository = "https://github.com/iamsauravsharma/tower_allowed_hosts"
description = "tower allowed hosts layer"
license = "MIT"
readme = "README.MD"

[dependencies]
http = "0.2.9"
pin-project = "1.1.3"
regex = { version = "1.9.3", optional = true }
thiserror = "1.0.44"
tower = "0.4.13"

[features]
regex = ["dep:regex"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
